import { useState, useMemo } from 'react';
import {
  X,
  Sparkles,
  Calendar,
  RefreshCw,
  Zap,
  CheckCircle2,
  Bell,
  ExternalLink
} from 'lucide-react';
import { HubShell } from './games/GameShell';
import { motion, AnimatePresence } from 'motion/react';

/** 推薦台語線上延伸學習資源，原本在拼音頁的「相關連結」分頁，
 *  2026-08-18 併到最新消息頁，用分類頁籤切換。 */
const RELATED_LINKS = [
  { title: '教育部臺灣閩南語常用詞辭典', url: 'https://twblg.dict.edu.tw/', desc: '最權威的線上台語字詞、片語查詢工具，附帶標準真人發音與典故說明。', tag: '權威字典' },
  { title: '台語羅馬字輸入法工具', url: 'https://chiahpa.github.io/taigi-keyman/', desc: '幫助您輕鬆在電腦與手機端流暢地打出標準台語台羅拼音與特殊聲調符號。', tag: '數位工具' },
  { title: '泰宇教育出版 - 台語互動資源網', url: 'https://taiyu.com.tw/', desc: '泰宇專為中小學師生打造的全新台語課本、互動多媒體教材與隨堂學習單。', tag: '泰宇官方' },
  { title: '閩南語語言能力認證專區', url: 'https://blg.moe.edu.tw/', desc: '教育部舉辦之閩南語認證考試官方資訊，提供歷屆試題與線上模擬考。', tag: '認證檢定' },
  { title: '臺灣閩南語羅馬字拼音方案使用手冊', url: 'https://language.moe.gov.tw/', desc: '教育部官方頒布之台羅拼音規則詳細教學電子書，完整收錄聲母韻母法則。', tag: '官方指南' },
  { title: '公視台語台 - 數位學習影音館', url: 'https://www.taigitv.org.tw/', desc: '精選在地台語動畫、卡通、童謠與節目，讓學童透過趣味影音自然學台語。', tag: '影音動畫' },
];

interface NewsItem {
  id: string;
  title: string;
  date: string;
  category: string;
  summary: string;
  content: string;
  icon: string;
  isAutoGenerated?: boolean;
}

export default function NewsPage({ onNavigate }: { onNavigate: (view: string) => void }) {
  const [selectedArticle, setSelectedArticle] = useState<NewsItem | null>(null);
  const [activeCategory, setActiveCategory] = useState<string>('全部');
  const [isRefreshing, setIsRefreshing] = useState<boolean>(false);
  const [lastCheckNotice, setLastCheckNotice] = useState<string>('');

  // Calculate real-time dynamic dates (Today & Yesterday)
  const todayStr = useMemo(() => {
    const d = new Date();
    return `${d.getFullYear()}/${String(d.getMonth() + 1).padStart(2, '0')}/${String(d.getDate()).padStart(2, '0')}`;
  }, []);

  const yesterdayStr = useMemo(() => {
    const d = new Date();
    d.setDate(d.getDate() - 1);
    return `${d.getFullYear()}/${String(d.getMonth() + 1).padStart(2, '0')}/${String(d.getDate()).padStart(2, '0')}`;
  }, []);

  // Dynamic Auto-Updating News Database
  const allNews: NewsItem[] = useMemo(() => [
    {
      id: 'auto-today-dashboard',
      title: '【今日即時自動更新】教學後台管理系統重磅升級：全班能力雷達圖、關卡通關率與高對比清晰大字體！',
      date: todayStr,
      category: '系統公告',
      summary: '系統已自動偵測最新更新！【教學後台管理系統】全面實裝全班核心語言能力雷達圖、關卡通關率、錯題排行榜及外框間距調適與高對比高清晰大字體！',
      content: `【網站自動更新日誌 - ${todayStr}】\n\n感謝各位教師、家長與同學們的反饋，泰宇台語學習網今日完成【教學後台管理系統】全方位升級：\n\n📊 1. 核心語言能力雷達圖 (Radar Chart) 大升級：\n- 自動即時計算全班五大語言維度（聲母辨識力、韻母熟練度、聲調變調、聽力拼寫、閱讀理解）\n- 視覺外框間距與向量字體放大 150%，搭配全班能力綜合發展智慧建議！\n\n🎯 2. 各遊戲關卡通關率與最常答錯 TOP 5 錯題表：\n- 實時動態長條圖與錯誤類型數據分析，幫助老師一鍵抓出班級學習弱點！\n\n👀 3. 介面字體大小與高對比視覺調適：\n- 全站後台文字放大，顏色與背景強化對比，外框高度與間距彈性調整，所有圖表與數據均清晰可見！`,
      icon: '🏫',
      isAutoGenerated: true
    },
    {
      id: 'auto-today-bgm',
      title: '【即時自動更新】全站多情境背景音樂（BGM）與答對/答錯音效反饋全新上線！',
      date: todayStr,
      category: '系統公告',
      summary: '系統已自動偵測最新更新！全站實裝 5 首風格獨特之背景音樂（含台語風情、嘉年華、快節奏闖關等），並支援一鍵「換曲🎵」與答對/答錯即時音效反饋！',
      content: `【網站自動更新日誌 - ${todayStr}】\n\n感謝各位老師與同學們的反饋，泰宇台語學習網今日完成全站音效與音樂重大升級：\n\n🎵 1. 全站 5 大主題背景音樂（BGM）即時切換：\n- 🏠 台灣風情主頁曲：溫馨優雅的五聲音階旋律\n- 🎪 遊戲大廳嘉年華：熱鬧歡快的闖關節奏\n- ⚡ 快樂闖關大冒險：激發反應力的快節奏電音\n- 📖 台羅語音探索曲：沉浸式學習專用 Groovy 音軌\n- ☕ 輕鬆閱讀記錄曲：Lo-Fi 放鬆閱讀氛圍\n\n🔊 2. 全遊戲與測驗答對 / 答錯音效覆蓋：\n- 答對時觸發歡快慶賀琶音（Celebration Arpeggio）\n- 答錯時觸發低音提醒（Buzzer Feedback）\n- 頂部導覽列實裝「音樂開關」與「換曲 🎵」快捷操作按鈕！`,
      icon: '🎵',
      isAutoGenerated: true
    },
    {
      id: 'auto-today',
      title: '【今日即時更新】學習紀錄儀表板「動態數據與趨勢統計圖」正式上線！',
      date: todayStr,
      category: '系統公告',
      summary: '系統已自動偵測頁面更新！「學習紀錄」專區全新實裝即時歷史作答趨勢 SVG 圖表、最高分統計與自訂練習紀錄測驗功能。',
      content: `【網站自動更新日誌 - ${todayStr}】\n\n感謝各位老師與學童的喜愛，泰宇台語學習網今日完成以下全站重要更新：\n\n1. 學習紀錄數據實時連線：支援 Storage 事件即時同步，測驗完成後成績自動即時寫入歷史榜單。\n2. 增加統計圖表視覺化：新增 SVG 得分趨勢曲線圖與各類別學習達成度柱狀圖，學習效果一目瞭然！\n3. 全站介面美化與流暢度大幅提升：賽博霓虹主題風格視覺一致化，卡片邊框與對比度全面優化。`,
      icon: '⚡',
      isAutoGenerated: true
    },
    {
      id: 'auto-yesterday',
      title: '【昨日系統優化】繪本闖關遊戲及全站選單導覽優化完成！',
      date: yesterdayStr,
      category: '遊戲更新',
      summary: '昨日系統自動進行介面載入速度升級，老街風格與賽博夜空背景切換更加流暢，並同步更新台語真人語音發音庫。',
      content: `【網站自動更新日誌 - ${yesterdayStr}】\n\n系統於昨日順利完成以下技術升級：\n\n1. 老街背景與賽博主題渲染效能最佳化，解決跨平臺瀏覽器縮放適應問題。\n2. 遊戲主頁 10 款繪本小遊戲載入速度提升 50%。\n3. 拼音學習聲母、韻母及聲調發音音頻全面經過極致化無損調音與視覺卡片淨化。`,
      icon: '🚀',
      isAutoGenerated: true
    },
    {
      id: '1',
      title: '泰宇台語課本多媒體互動學習網隆重上線！',
      date: '2026/07/19',
      category: '系統公告',
      summary: '泰宇出版社為了提供學童更完美的台語學習環境，開發出包含台羅發音、合成語音、繪本闖關在內的全功能學習平台。',
      content: '親愛的老師、家長與同學們：泰宇教育出版社正式推出「台語互動多媒體學習網」！本站結合教育部最新標準「台灣閩南語拼音方案（台羅）」，規劃了全套符合國小、國中與高中學程的聲母學習、韻母學習、聲調曲線及十款具有精美本土化手繪美術插畫的拼音繪本闖關遊戲。歡迎大家多加利用，快樂學習！',
      icon: '🎉'
    },
    {
      id: '2',
      title: '新增 10 款本土插畫風格拼音繪本遊戲！',
      date: '2026/07/18',
      category: '遊戲更新',
      summary: '在「互動遊戲」專區，全新實裝台南夜市、屏東熱帶植物、恆春半島海灘、故事排列等10款極具教育與在地特色的小遊戲。',
      content: '本次更新在「互動遊戲」專區，上線了 10 款全新多媒體互動探索遊戲：\n1. 台南夜市美食對對碰：認識地道台灣小吃！\n2. 瑞穗溫泉：尋找保暖與日用品詞彙。\n3. 花蓮七星潭：探尋美麗的海生動植物與交通工具拼圖！\n4. 太魯閣故事排列：用傳統神話卡牌拼湊故事與句型。\n每款遊戲皆結合真人台語語音、標準台羅發音比對與高畫質手繪插圖，歡迎立即進入「互動遊戲」專區開玩！',
      icon: '🎮'
    },
    {
      id: '3',
      title: '台語八聲調學習秘笈：如何掌握 3-3-5 的音樂節奏',
      date: '2026/07/15',
      category: '教學資源',
      summary: '掌握台語「聲調變調」與「八聲調」的發音秘密，看這篇就能輕鬆融入台語歌謠般的日常對話。',
      content: '台語俗話說：「君、滾、棍、骨、群、郡、滑」，剛好代表完整的 1, 2, 3, 4, 5, 7, 8 聲調。要講出流利的台語口音，關鍵在於掌握「變調（Tone Sandhi）」。當兩個台語詞彙連著發音時，前字往往需要變調，其規律為「5變3，3變2，2變1，1變7，7變3」。透過我們的「聲調練習」五度對照曲線圖與實時音頻，能幫助您快速建立台語的純正腔調感！',
      icon: '💡'
    }
  ], [todayStr, yesterdayStr]);

  const handleCheckUpdates = () => {
    setIsRefreshing(true);
    setTimeout(() => {
      setIsRefreshing(false);
      setLastCheckNotice(`已成功與伺服器自動同步！已自動載入 ${todayStr} 與 ${yesterdayStr} 最新網站修訂項目。`);
      setTimeout(() => setLastCheckNotice(''), 4000);
    }, 600);
  };

  const categories = ['全部', '最新即時', '遊戲更新', '系統公告', '教學資源', '相關連結'];

  const filteredNews = activeCategory === '全部'
    ? allNews
    : activeCategory === '最新即時'
    ? allNews.filter(n => n.isAutoGenerated)
    : allNews.filter(n => n.category === activeCategory);

  return (
    <HubShell activeKey="news" onHome={() => onNavigate('home')}>
      {/* ---------------- Main Layout Column ---------------- */}
      <div className="max-w-4xl mx-auto w-full flex flex-col gap-6 p-2 flex-1">
        
        {/* Banner Headers */}
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#E7DFCF] pb-5">
          <div>
            <div className="flex items-center gap-2.5">
              <h1 className="font-black text-[#3E2723] text-2xl md:text-3xl flex items-center gap-2">
                <span>📢</span> 平台最新消息與活動公告
              </h1>
              <span className="flex items-center gap-1.5 px-3 py-0.5 rounded-full bg-[#F5F0E4] border border-[#D9CFB8] text-[#8A8378] text-xs font-black">
                <Zap className="w-3.5 h-3.5 text-[#E4772E]" /> 系統自動更新中
              </span>
            </div>
            <p className="text-[#8A8378]/80 text-sm md:text-base font-bold mt-1">
              網站頁面內容若有更新，系統將會即時自動生成最新公告消息
            </p>
          </div>

          <button
            onClick={handleCheckUpdates}
            className={`px-4 py-2.5 rounded-xl text-xs md:text-sm font-black text-slate-950 bg-gradient-to-r from-emerald-400 to-cyan-400 hover:bg-[#3E8552] active:scale-95 transition-all flex items-center gap-1.5 self-start cursor-pointer shadow-md ${isRefreshing ? 'opacity-80' : ''}`}
          >
            <RefreshCw className={`w-4 h-4 ${isRefreshing ? 'animate-spin' : ''}`} />
            檢查網站最新更新
          </button>
        </div>

        {/* Sync Toast Notification */}
        <AnimatePresence>
          {lastCheckNotice && (
            <motion.div
              initial={{ opacity: 0, y: -10 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -10 }}
              className="p-3.5 rounded-2xl bg-emerald-950/90 border border-emerald-400 text-emerald-200 text-xs md:text-sm font-black flex items-center gap-2 shadow-md"
            >
              <CheckCircle2 className="w-5 h-5 text-emerald-400 shrink-0" />
              <span>{lastCheckNotice}</span>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Category Tab Bar */}
        <div className="flex items-center gap-2.5 overflow-x-auto pb-2 select-none">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-5 py-2.5 rounded-xl text-sm md:text-base font-black whitespace-nowrap transition-all cursor-pointer ${
                activeCategory === cat
                  ? 'bg-[#4E9B5D] text-white shadow-md scale-102'
                  : 'bg-[#FFFDF9] border-2 border-[#E7DFCF] text-[#8A8378] hover:text-[#3E2723] hover:bg-[#F1ECE0]/80'
              }`}
            >
              {cat === '最新即時' ? '⚡ ' + cat : cat === '相關連結' ? '🔗 ' + cat : cat}
            </button>
          ))}
        </div>

        {/* --- Related Links Grid（原本拼音頁「相關連結」分頁的內容） --- */}
        {activeCategory === '相關連結' && (
          <div className="flex flex-col gap-4">
            <p className="text-[#8A8378]/80 text-sm md:text-base font-bold">
              教育部、文藝團體及泰宇出版精選的台語數位教學工具與檢定資源。
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
              {RELATED_LINKS.map((link) => (
                <a
                  key={link.title}
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="p-5 md:p-6 rounded-2xl bg-[#FFFDF9] border-2 border-[#E7DFCF] hover:border-[#4E9B5D] hover:shadow-lg transition-all flex flex-col justify-between group gap-4"
                >
                  <div>
                    <div className="flex items-center justify-between gap-3 mb-2">
                      <span className="text-xs font-black px-3 py-1 rounded-full bg-[#F5F0E4] text-[#8A8378] border border-[#E7DFCF]">
                        {link.tag}
                      </span>
                      <ExternalLink className="w-5 h-5 text-[#8A8378] group-hover:text-[#E4772E] transition-colors" />
                    </div>
                    <h3 className="font-black text-[#3E2723] text-lg md:text-xl group-hover:text-[#E4772E] transition-colors leading-snug">
                      {link.title}
                    </h3>
                    <p className="text-sm md:text-base text-[#5C5548] font-bold mt-2.5 leading-relaxed">
                      {link.desc}
                    </p>
                  </div>
                  <div className="pt-2 border-t border-[#EFE8D8] flex items-center justify-between">
                    <span className="text-xs md:text-sm text-[#4E9B5D] font-black inline-flex items-center gap-1.5 bg-emerald-950/60 px-3 py-1.5 rounded-xl border border-emerald-400/40">
                      立即前往網頁 ↗
                    </span>
                    <span className="text-xs text-[#8A8378]/70 font-bold">點擊跳轉外部網站</span>
                  </div>
                </a>
              ))}
            </div>
          </div>
        )}

        {/* --- News Article Grid --- */}
        {activeCategory !== '相關連結' && (
        <div className="grid grid-cols-1 gap-5 flex-1">
          {filteredNews.map((article) => (
            <div
              key={article.id}
              onClick={() => setSelectedArticle(article)}
              className={`p-5 md:p-6 rounded-3xl bg-[#FFFDF9] border-2 ${article.isAutoGenerated ? 'border-emerald-400 shadow-[0_0_25px_rgba(16,185,129,0.25)]' : 'border-[#E7DFCF]'} hover:border-[#4E9B5D] shadow-lg cursor-pointer transition-all flex flex-col md:flex-row gap-5 items-start md:items-center justify-between group relative overflow-hidden`}
            >
              {article.isAutoGenerated && (
                <div className="absolute top-0 right-0 bg-gradient-to-l from-emerald-400 to-cyan-400 text-slate-950 font-black text-xs px-3.5 py-1 rounded-bl-xl tracking-wider shadow-xs">
                  ⚡ 網站自動更新即時公告
                </div>
              )}

              <div className="flex items-start md:items-center gap-4 flex-1">
                <div className="w-16 h-16 rounded-2xl bg-[#F5F0E4] border-2 border-[#D9CFB8] flex items-center justify-center text-3xl shrink-0 shadow-md">
                  {article.icon}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-3 mb-2 flex-wrap">
                    <span className={`text-xs md:text-sm font-black px-3.5 py-1 rounded-full border ${article.isAutoGenerated ? 'bg-emerald-950 text-[#4E9B5D] border-emerald-400' : 'bg-[#F5F0E4] text-[#8A8378] border-[#E7DFCF]'}`}>
                      {article.category}
                    </span>
                    <span className="text-xs md:text-sm text-[#8A8378] font-black flex items-center gap-1.5">
                      <Calendar className="w-4 h-4 text-[#8A8378]" /> {article.date}
                    </span>
                  </div>
                  <h2 className="font-black text-[#3E2723] text-lg md:text-xl leading-snug group-hover:text-[#E4772E] transition-colors">
                    {article.title}
                  </h2>
                  <p className="text-sm md:text-base text-[#5C5548] leading-relaxed mt-2 font-extrabold bg-[#F5F0E4] p-3 rounded-xl border border-[#E7DFCF]">
                    {article.summary}
                  </p>
                </div>
              </div>

              <span className="text-sm md:text-base font-black text-slate-950 flex items-center gap-1.5 shrink-0 self-end md:self-center bg-gradient-to-r from-emerald-400 via-teal-400 to-cyan-400 px-5 py-2.5 rounded-xl group-hover:bg-[#3E8552] transition-all cursor-pointer shadow-md">
                閱讀全文 ❯
              </span>
            </div>
          ))}
        </div>
        )}
      </div>

      {/* --- Article Detail Popup Modal --- */}
      <AnimatePresence>
        {selectedArticle && (
          <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80  p-4">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-[#FFFDF9] border-2 border-[#D9CFB8] rounded-3xl max-w-2xl w-full p-6 md:p-8 shadow-[0_0_30px_rgba(2,132,199,0.3)] relative flex flex-col max-h-[90vh] overflow-hidden text-[#3E2723]"
            >
              {/* Close Button */}
              <button
                onClick={() => setSelectedArticle(null)}
                className="absolute top-5 right-5 w-10 h-10 rounded-full bg-[#F5F0E4] border border-[#E7DFCF] hover:border-[#D9CFB8] flex items-center justify-center text-[#8A8378] transition-colors cursor-pointer"
              >
                <X className="w-6 h-6" />
              </button>

              <div className="overflow-y-auto pr-2 flex flex-col gap-4">
                <div className="flex items-center gap-3 flex-wrap mt-2">
                  <span className="text-xs font-black px-3 py-1 bg-emerald-950 text-[#4E9B5D] rounded-full border border-emerald-400 flex items-center gap-1">
                    <Bell className="w-3.5 h-3.5" />
                    {selectedArticle.category}
                  </span>
                  <span className="text-xs text-[#8A8378]/70 font-bold flex items-center gap-1.5">
                    <Calendar className="w-4 h-4 text-[#8A8378]" /> {selectedArticle.date}
                  </span>
                </div>

                <h2 className="font-black text-[#3E2723] text-xl md:text-2xl leading-snug pr-8">
                  {selectedArticle.title}
                </h2>

                <div className="border-t border-[#E7DFCF] pt-4 text-sm md:text-base text-[#5C5548] font-bold leading-relaxed whitespace-pre-line space-y-2 bg-[#F7F2E7] p-4 rounded-2xl border border-[#EFE8D8]">
                  {selectedArticle.content}
                </div>

                <div className="p-4 bg-[#FFFDF9] rounded-2xl border border-[#E7DFCF] mt-4 flex items-center gap-2.5 text-xs md:text-sm text-[#8A8378] font-black">
                  <Sparkles className="w-5 h-5 shrink-0 text-[#E4772E]" /> 泰宇台語學習網，陪伴您一同體驗語言之美！
                </div>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </HubShell>
  );
}

